### ISSUE TITLE
[NX] 학과 Top 10 / Top 100 키워드 추출 코드 구현

### ISSUE THREAD

**Issue by ghost** [themajormap/majormap#16]
## TO BE ADDED
`python extract_keyword [region] [University Name] [Department Name] -n 10` 으로 top 10 keyword를 추출하는 코드 구현

## TASKS
- [ ] jupyter notebook에서 University Name, Department Name으로 top 10 / top 100 keyword를 추출하는 로직 구현
- [ ] 해당 로직을 extract_keyword.py로 재구현
- [ ] Princeton University / Chemistry에 대해 테스트 수행

## SCHEDULE
* 10월 8일 까지 완료

## ISSUE CHANGE LOG
* 2020/10/05 20:50 - 최초 작성 by 제임스
