### ISSUE TITLE
회원가입 양식에 성별 선택 필드 추가

### ISSUE THREAD

**Issue by james-majormap** [themajormap/majormap#2]
## AS IS
- 회원 가입 양식에 성별 선택 필드 없음

## TO BE
- 회원 가입 양식에 성별 선택 필드 추가

![스크린샷 2020-07-02 오후 4 22 26](https://user-images.githubusercontent.com/66929386/86329633-633d8280-bc81-11ea-9e60-a8d8cc321c60.png)

## TASKS
- [x] 데이터베이스 User 테이블에 성별 필드 추가
- [x] ~백엔드 회원가입 API가 성별 필드를 인식하도록 수정~ --> 필요 없었음
- [x] 프론트엔드 회원가입/회원정보수정 양식에 성별 필드 추가
- [x] 프론트엔드 회원가입/회원정보수정 폼 검증 로직에 성별이 빈 값이 아닌 것을 검증하도록 추가

## SCHEDULE
* 7월 3일 까지 완료

## ISSUE CHANGE LOG
* 2020/07/02 16:35 - 최초 작성 by James
* 2020/07/02 11:52 - TASKS 수정 by James
