### ISSUE TITLE
[GS] 프론트엔드 이메일로 회원가입 구현

### ISSUE THREAD

**Issue by ghost** [themajormap/majormap#20]
## TO BE ADDED
회원가입 / 이메일 인증 부분을 백엔드와 연동하여 구현

## TASKS
- [x] 화원가입 post 요청 구현
- [x] 이메일 인증 메일 발송 요청 구현
- [x] 회원가입 실패 처리 구현 (중복되는 이메일)
- [x] 이메일 전송 실패 처리 구현
- [ ] 비밀번호 확인 폼 검증
~[ ] 인증되지 않은 이메일 로그인 시도에 대한 체크 구현~ 로그인 기능 구현 이슈 별도 생성 예정

## SCHEDULE
* ~10월 07일 까지 완료~
* 10월 20일 까지 완료

## ISSUE CHANGE LOG
* 2020/10/06 11:15 - 최초 작성 by 제임스
* 2020/10/06 15:40 - Task 추가 by 제임스
* 2020/10/16 14:15 - 일정 변경 by 제임스

**Comment by ghost** [comment]
Task 수정
- [ ] 회원가입 실패 처리 구현 (중복되는 이메일)
- [ ] 이메일 전송 실패 처리 구현
- [ ] 비밀번호 확인 폼 검증
~[ ] 인증되지 않은 이메일 로그인 시도에 대한 체크 구현~ 로그인 기능 구현 이슈 별도 생성 예정
