### ISSUE TITLE
[KS] 마이페이지 > 학업계획서 > 학업계획서 만들기 > 직업 선택 페이지 구현

### ISSUE THREAD

**Issue by ghost** [themajormap/majormap#22]
## TO BE ADDED
마이페이지 > 학업계획서 > 학업계획서 만들기 > 직업 선택 페이지

## TASKS
- [x] 마크업 및 스타일링
- [x] 직업 리스트 dummy data를 활용하여 직업 선택 로직 구현
- [x] dummy data를 반환하는 function을 활용해 자동완성 기능 구현
- [x] 기본적인 폼 값 검증 및 다음 버튼 활성화

## SCHEDULE
* 10월 16일 까지 완료

## ISSUE CHANGE LOG
* 2020/10/06 12:00 - 최초 작성 by 제임스

**Comment by ghost** [comment]
자동 완성 더미데이터 예시

```
if (param === '언') {
  return [
    {name: '언어학연구원', category: '인문'},
    {name: '언어치료사', category: '의료보건'}
  ]
}

if (param === '컴') {
  return [
    {name: '컴퓨터프로그래머', category: '공학'}
  ]
}
```
