### ISSUE TITLE
[KS] 마이페이지 > 학업계획서 > 학업계획서 만들기 > 직업유사도 페이지 구현

### ISSUE THREAD

**Issue by ghost** [themajormap/majormap#23]
## TO BE ADDED
마이페이지 > 학업계획서 > 학업계획서 만들기 > 직업유사도 페이지

## TASKS
- [ ] 해외대학 princeton university graph data json파일을 이용해 직업 유사도 dummy data 생성 (대체)
- [x] 학과 유사도 json파일을 이용해 직업 유사도 dummy data 생성
- [x] json 파일을 major-echart 컴포넌트에서 사용할 수 있도록 가공해주는 로직 구현
- [x] 직업 선택 시 선택한 직업 목록 구현
- [x] 마크업 및 스타일링

## SCHEDULE
* 10월 16일 까지 완료

## ISSUE CHANGE LOG
* 2020/10/06 12:00 - 최초 작성 by 제임스
* 2020/10/07 15:50 - TASKS 수정 by 제이크
