### ISSUE TITLE
[GS] University, Department 리팩토링 및 College 추가

### ISSUE THREAD

**Issue by ghost** [themajormap/majormap#29]
## AS IS
pagination 및 hyperlink 기능 구현 안됨.

각 ModelViewSet의 retrieve 함수가 부모 클래스의 동작과 동일하므로 구현 할 필요 없음.

## TO BE
* pagination 및 hyperlink를 지원할 수 있도록 설정을 변경함. (HyperlinkedModelSerializer 이용)

* 각 모델에 대하여 ListSerializer와 DetailSerializer를 만들 것.

* HyperlinkedModelSerialializer의 경우 endpoint 구조가 Framework 기본값과 다를 경우 오류가 잘 발생하므로 우선 ListSerializer에만 적용.

* ListSerializer의 fields는 'url', 'id', 모델 고유필드, related field, url만 들어감. JSONField는 제외. (University의 경우 ('url', 'id', 'name', 'region', 'state', 'colleges') 가 됨)

* DetailSerializer는 기존대로 ModelSerializer를 이용하고 fields = '__all__' 적용.

* 각 ModelViewSet의 retrieve 함수 삭제. list 함수 또한 필터링 로직을 get_queryset 함수나 FilterClass쪽으로 옮기고 삭제 가능하면 삭제

* URL Routing Rule은 가급적 Django REST Framework에서 사용하는 Convention을 따르도록 수정 (router에 넘겨주는 basename은 모델의 복수형이 아니라 단수형으로 함. URL에 표시되는 endpoint 주소는 반대로 복수형으로 함.)

Pagination 설정 문서: https://www.django-rest-framework.org/api-guide/pagination/
DEFAULT_PAGINATION_CLASS: rest_framework.pagination.LimitOffsetPagination (코드가 복잡해지지만 Clinet side에서 유연한 조정 가능)
PAGE_SIZE: 20

HyperlinkedModelSerialiser 문서: https://www.django-rest-framework.org/api-guide/serializers/#hyperlinkedmodelserializer

## TASKS
- [x] Pagination이 적용되도록 settings파일 수정
- [x] University, College, Department 모델에 대한 List/Detail Serializer 구현
- [x] 각 ListSerializer를 HyperlinkedModelSerializer 를 상속하도록 조정
- [x] ModelViewSet의 코드 간소화
- [x] API 변경사항에 대해 stoplight 문서 업데이트

## SCHEDULE
* 10월 16일 까지 완료

## ISSUE CHANGE LOG
* 2020/10/14 14:00 - 최초 작성 by 제임스
