### ISSUE TITLE
[GS] 프론트엔드 이메일 주소 및 비밀번호로 로그인 구현

### ISSUE THREAD

**Issue by ghost** [themajormap/majormap#33]
## TO BE ADDED
로그인 모달에서 이메일 주소 및 비밀번호로 로그인할 수 있는 기능 추가 

## TASKS
- [x] 로그인 성공 시 dashboard page로 redirect 할 수 있도록 라우터 및 dummy page 구성
- [x] 로그인 실패 시 오류메시지 출력
- [x] 예외처리를 위한 redux-form 라이브러리 연동 구성

## SCHEDULE
* 10월 20일 까지 완료

## ISSUE CHANGE LOG
* 2020/10/16 14:20 - 최초 작성 by 제임스
