### ISSUE TITLE
검색 결과페이지 개편 - 전공이름별 대학 리스트 페이지 개발

### ISSUE THREAD

**Issue by james-majormap** [themajormap/majormap#4]
## AS IS
통합검색 및 전공검색에서 전공 이름을 클릭할 경우 페이지 이동 없이 대학 리스트가 가나다순으로 펼쳐짐

## TO BE
검색 결과에서 전공 이름을 클릭할 경우 1 depth를 추가하여 전공이름별 대학 리스트 페이지로 이동

## TO BE ADDED
특정 전공 이름 (ex. 경영학과)의 학과를 개설하고 있는 대학의 목록을 보여주는 페이지 구현
![주석 2020-07-03 234406](https://user-images.githubusercontent.com/66929386/86479670-8d796800-bd87-11ea-9974-d35730f4f104.png)

## TASKS
- [x] Frontend 라우터에 /majors/<전공명>/universities/ 엔드포인트 추가하고 view 컴포넌트에 연결
- [ ] ~<전공명>이 존재하지 않을 경우 404페이지 보이도록 구성~ => 검색결과 0개로 나오도록 구현함
- [ ] ~검색어에 따라 순위가 바뀌도록 검색 Backend 검색 알고리즘 수정, 예를들어 서울대학교 경영학과라고 검색하면 서울대학교가 먼저 노출되고 고려대학교 경영학과라고 검색하면 고려대학교가 먼저 노출되고 경영학과 라고 검색하면 조회순으로 노출되도록~ => 별도 이슈로 진행

## SCHEDULE
* 7월 6일 까지 완료

## ISSUE CHANGE LOG
* 2020/07/03 23:50 - 최초 작성 by James
* 2020/07/06 11:20 - TASKS 수정 by James
