### ISSUE TITLE
[GS] 선호검사, UniversityInfo EndPoints 테스트 추가

### ISSUE THREAD

**Issue by seongminchoob** [themajormap/majormap#44]
## TO BE ADDED
- masters fake 데이터 추가 기능
- UniversityInfo test 추가
- 적성검사 test 추가

## TASKS
- [x] University Info test 추가
- [x] Department data test 추가
- [x] 작성검사 test 추가

## SCHEDULE
* 10월 22일 까지 완료

## ISSUE CHANGE LOG
* 2020/10/22 18:30 - 최초 작성 by 데이빗
